jobs:
  codecov:
    needs: tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Download coverage artifacts
      uses: actions/download-artifact@v3
    - continue-on-error: true
      name: Upload coverage to Codecov.io
      uses: Wandalen/wretry.action@v1.3.0
      with:
        action: codecov/codecov-action@v3
        attempt_delay: 30000
        attempt_limit: 5
        with: 'fail_ci_if_error: true

          '
  tests:
    env:
      MAVEN_OPTS: -Xmx1024M
    name: Run ${{ matrix.type }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout codebase
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      env:
        TEST_FLAGS: ${{ matrix.mvnflags }}
      name: Run Maven ${{ matrix.type }}
      run: mvn --no-transfer-progress -V install -P-assembly -Pcoverage-report $TEST_FLAGS
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload Results of ${{ matrix.type }} to Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.type }} results
        path: ${{ matrix.resultsdir }}
    - continue-on-error: true
      name: Upload code coverage report to Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.type }} coverage report
        path: dspace/target/site/jacoco-aggregate/jacoco.xml
        retention-days: 14
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 11
          mvnflags: -DskipUnitTests=false -Dsurefire.rerunFailingTestsCount=2
          resultsdir: '**/target/surefire-reports/**'
          type: Unit Tests
        - java: 11
          mvnflags: -DskipIntegrationTests=false -Denforcer.skip=true -Dcheckstyle.skip=true
            -Dlicense.skip=true -Dxml.skip=true -Dfailsafe.rerunFailingTestsCount=2
          resultsdir: '**/target/failsafe-reports/**'
          type: Integration Tests
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
permissions:
  contents: read
