jobs:
  dspace:
    if: github.repository == 'dspace/dspace'
    needs: dspace-dependencies
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      REDEPLOY_DEMO_URL: ${{ secrets.REDEPLOY_DEMO_URL }}
      REDEPLOY_SANDBOX_URL: ${{ secrets.REDEPLOY_SANDBOX_URL }}
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      build_id: dspace
      dockerfile_path: ./Dockerfile
      image_name: dspace/dspace
  dspace-cli:
    if: github.repository == 'dspace/dspace'
    needs: dspace-dependencies
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      build_id: dspace-cli
      dockerfile_path: ./Dockerfile.cli
      image_name: dspace/dspace-cli
  dspace-dependencies:
    if: github.repository == 'dspace/dspace'
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      build_id: dspace-dependencies
      dockerfile_path: ./Dockerfile.dependencies
      image_name: dspace/dspace-dependencies
  dspace-postgres-pgcrypto:
    if: github.repository == 'dspace/dspace'
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      build_id: dspace-postgres-pgcrypto
      dockerfile_context: ./dspace/src/main/docker/dspace-postgres-pgcrypto/
      image_name: dspace/dspace-postgres-pgcrypto
  dspace-postgres-pgcrypto-loadsql:
    if: github.repository == 'dspace/dspace'
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      build_id: dspace-postgres-pgcrypto-loadsql
      dockerfile_context: ./dspace/src/main/docker/dspace-postgres-pgcrypto-curl/
      image_name: dspace/dspace-postgres-pgcrypto
      tags_flavor: suffix=-loadsql
  dspace-solr:
    if: github.repository == 'dspace/dspace'
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      REDEPLOY_DEMO_URL: ${{ secrets.REDEPLOY_DEMO_SOLR_URL }}
      REDEPLOY_SANDBOX_URL: ${{ secrets.REDEPLOY_SANDBOX_SOLR_URL }}
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      build_id: dspace-solr
      dockerfile_additional_contexts: solrconfigs=./dspace/solr/
      dockerfile_path: ./dspace/src/main/docker/dspace-solr/Dockerfile
      image_name: dspace/dspace-solr
  dspace-test:
    if: github.repository == 'dspace/dspace'
    needs: dspace-dependencies
    secrets:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      build_id: dspace-test
      dockerfile_path: ./Dockerfile.test
      image_name: dspace/dspace
      tags_flavor: suffix=-test
name: Docker images
on:
  repository_dispatch:
    types: trigger-ga___docker.yml
permissions:
  contents: read
