jobs:
  automation:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: (contains(github.event.issue.labels.*.name, 'needs triage') || join(github.event.issue.labels.*.name)
        == '')
      name: Add issue to triage board
      uses: actions/add-to-project@v0.5.0
      with:
        github-token: ${{ secrets.TRIAGE_PROJECT_TOKEN }}
        project-url: https://github.com/orgs/DSpace/projects/24
name: Issue opened
on:
  repository_dispatch:
    types: trigger-ga___issue_opened.yml
permissions: {}
