jobs:
  triage:
    if: github.repository == 'dspace/dspace'
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Auto-label PRs with merge conflicts
      uses: prince-chrismc/label-merge-conflicts-action@v3
      with:
        conflict_comment: 'Hi @${author},

          Conflicts have been detected against the base branch.

          Please [resolve these conflicts](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts)
          as soon as you can. Thanks!

          '
        conflict_label_name: merge conflict
        github_token: ${{ secrets.GITHUB_TOKEN }}
name: Check for merge conflicts
on:
  repository_dispatch:
    types: trigger-ga___label_merge_conflicts.yml
permissions: {}
