jobs:
  port_pr:
    if: github.event.pull_request.merged
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Create backport pull requests
      uses: korthout/backport-action@v2
      with:
        copy_labels_pattern: .*
        github_token: ${{ secrets.PR_PORT_TOKEN }}
        label_pattern: ^port to ([^ ]+)$
        merge_commits: skip
        pull_description: 'Port of #${pull_number} by @${pull_author} to `${target_branch}`.'
        pull_title: '[Port ${target_branch}] ${pull_title}'
name: Port merged Pull Request
on:
  repository_dispatch:
    types: trigger-ga___port_merged_pull_request.yml
permissions:
  contents: write
  pull-requests: write
