jobs:
  automation:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Assign PR to creator
      uses: toshimaru/auto-author-assign@v2.0.1
name: Pull Request opened
on:
  repository_dispatch:
    types: trigger-ga___pull_request_opened.yml
permissions:
  pull-requests: write
